spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/simplemall;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # 해당하는 테이블이 있으면 DROP하고 새로 만들어준다.
    properties:
      hibernate:
#        show_sql: #system.out으로 출력함. 개발환경에서만 사용할 것.
        format_sql: true
        use_sql_comments: true  # querydsl이 생성하는 JPQL 쿼리를 보는 옵션
        default_batch_fetch_size: 100 # SQL IN절을 사용하여 한 번에 가져올 row 개수 설정.

logging:
  level:
    org.hibernate.SQL: debug # logger를 통해서 sql을 로깅함.
#    org.hibernate.type: trace  # jpa가 날리는 sql의 쿼리 파라미터를 알려주는 설정.